### ISSUE TITLE
Migrating to `yarn`

### ISSUE THREAD

**Issue by iamrajiv** [wechaty/docusaurus#1293]
There are several benefits in using `yarn` over `npm`, most notably:

- Yarn strongly binds package versions
- Yarn can install packages from a local cache, not requiring network config
  Yarn is almost twice as fast as npm because it parallelizes operations to maximize resource utilization so install times are much faster. The great part is that Yarn is caching everything.
- Monorepo support (multiple packages) without the requirement for Lerna

**Comment by iamrajiv** [comment]
@huan Any views on this.

**Comment by huan** [comment]
Hi @iamrajiv ,

Thanks for the recommendation!

However, I'm not a fan of Yarn and I think NPM is good enough, especially for the latest v7, which has huge improvements as the Yarn does.

And in the practice of wechaty community, we are always using polyrepos instead of the monorepo to maximum decouple all modules by github repos, and we will add package-lock.json to .gitignore all the time.

So, let's keep using NPM for our community, and appreciate for your efforts to make our development environment better!

**Comment by iamrajiv** [comment]
@huan oh yeah above points make sense.
