### ISSUE TITLE
Wechaty.js.org Link cannot displayed as expect.

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#1364]
We can not identify which is the link and which is not, for example:

![image](https://user-images.githubusercontent.com/6419514/137627375-40bc6545-6fe5-41f4-83cb-1edb87f5f2af.png)

I think the landing page team may change some CSS style by mistake. @Rohitesh-Kumar-Jain Could you help the landing page team to fix this problem? Thanks!

**Comment by Rohitesh-Kumar-Jain** [comment]
Not just here, https://wechaty.js.org/docs/howto/contact/#if-you-dont-know-where-to-start-from, links aren't visible as link styles throughout Wechaty.

I too think @encodeArnab and @sajenjeshan1222 may have made some mistake here.

**Comment by huan** [comment]
Yes, almost all of the docs website links are broken now (invisible links everywhere). 

Please help our website fix it ASAP.

Thank you very much.

**Comment by sajen-k** [comment]
@huan and @lijiarui We will fix this issue soon.  Since the new lading page required some CSS changes as we showed in the figma file we changed the `custom.css` file, We will fix this issue soon. Thank you.

**Comment by huan** [comment]
@sajenjeshan1222 Thanks!

Could we limit our landing page change only related to the website root, and do not affect other pages?

For example, I'd like to do not to change all the footers for our docusaurus pages.

Because we are testing our landing page, so it would be better to leave other pages as they are.
