### ISSUE TITLE
PR提了都一个月了，不继续审核了？

### ISSUE THREAD

**Issue by chenj-freedom** [wechaty/docusaurus#582]

**Comment by huan** [comment]
Please wait for @lijiarui to review. She's quite busy those weeks so we can not have enough resources to review the blog posts from our community.

Thank you very much for your patient.

**Comment by huan** [comment]
We have too many PRs in our queue due to our busy schedule, so I review & merge most of them today.

The PRs that have been merged are listed below:

1. https://github.com/wechaty/wechaty.js.org/pull/307, blog URL: <https://wechaty.js.org/2020/07/02/wechat-bot-in-ten-minutes>
1. https://github.com/wechaty/wechaty.js.org/pull/379, blog URL: <https://wechaty.js.org/2020/07/23/kuakua-wechaty>
1. https://github.com/wechaty/wechaty.js.org/pull/488, blog URL: <https://wechaty.js.org/2020/08/22/market-wechat-robot>
1. https://github.com/wechaty/wechaty.js.org/pull/505, blog URL: <https://wechaty.js.org/2020/08/31/wechaty-english-learning-assistant>
1. https://github.com/wechaty/wechaty.js.org/pull/525, blog URL: <https://wechaty.js.org/2020/09/14/ads-filer-groupbot>
1. https://github.com/wechaty/wechaty.js.org/pull/526, blog URL: <https://wechaty.js.org/2020/09/14/my-first-wechaty-bot>
1. https://github.com/wechaty/wechaty.js.org/pull/554, blog URL: <https://wechaty.js.org/2020/09/30/wechat-file-schedule-box-clafixed>
1. https://github.com/wechaty/wechaty.js.org/pull/569, blog URL: <https://wechaty.js.org/2020/10/15/wechaty-wangke-bot>
1. https://github.com/wechaty/wechaty.js.org/pull/572, blog URL: <https://wechaty.js.org/2020/10/22/wechat-fanli-robot>
1. https://github.com/wechaty/wechaty.js.org/pull/576, blog URL: <https://wechaty.js.org/2020/10/22/wetchat-bot-chat>
1. https://github.com/wechaty/wechaty.js.org/pull/580, blog URL: <https://wechaty.js.org/2020/10/30/daily-message-and-chatbot>
1. https://github.com/wechaty/wechaty.js.org/pull/586, blog URL: <https://wechaty.js.org/2020/11/03/lets-water-bot>

@lijiarui Please review if you need any additional follow-ups, and feel free to close this issue after everything is OK.

**Comment by huan** [comment]
Closed this issue because all qualified PRs have been merged, cheers!
