### ISSUE TITLE
When hover at docs, cannot get the doc catalogue

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#883]
Web Version:
![image](https://user-images.githubusercontent.com/6419514/119232061-5a35f800-bb56-11eb-8556-0ecfa170316e.png)

Mobile Version:

![image](https://user-images.githubusercontent.com/6419514/119232089-78035d00-bb56-11eb-93cc-e9396db73b4d.png)

**Comment by sbis04** [comment]
I have also noticed this today

**Comment by huan** [comment]
I try to reproduce it locally, but it seems in my local box it works without this problem.

Is there anyone who can reproduce this problem locally?

**Comment by sbis04** [comment]
I have also tried locally just now and here it appears fine, but on the deployed version of the docs it seems to be broken.

<img width="1438" alt="Screenshot 2021-05-22 at 9 17 30 PM" src="https://user-images.githubusercontent.com/43280874/119232532-26050c00-bb43-11eb-9899-3042f32656b0.png">

**Comment by sbis04** [comment]
@huan  I found a solution on Stack Overflow regarding this: https://stackoverflow.com/questions/52493058/dropdown-is-hidden-behind-image

**Comment by huan** [comment]
@sbis04 Thank you very much for investigating the problem and creating the PR!

However, I believe that we have to make sure what the problem is before we try to fix it, which means that we need to be able to reproduce this problem locally first.

I will try to re-trigger the deploy again to see if another deployment can fix this problem, or let's continue monitoring this issue and try to reproduce it locally.

**Comment by huan** [comment]
After a re-deploy for our site (v0.8.280, see: https://wechaty.js.org/manifest.json), this issue has gone.

It's wired but I guess the reason is related to the GitHub pages and the deployment process.

**Comment by lijiarui** [comment]
Cool, it seems it is fixed. Thanks all and I will close this issue!
